project_id = "zhduiylpsfdswfsoqdba"

[functions.create-student]
verify_jwt = true

[functions.create-parent]
verify_jwt = true

[functions.seed-test-users]
verify_jwt = false

[functions.seed-sa-data]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false
