// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irkpbvuqkpdxwrkrdvnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlya3BidnVxa3BkeHdya3Jkdm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzg1MDYsImV4cCI6MjA2ODg1NDUwNn0.hrMvqxbcundLLj-vZ1FtIJTw4QYKDn6XO9QUMfoEQ_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});